sudo: required

services:
  - docker

before_install:
  - docker build -t olehhutsuliak/docker-practice -f Dockerfile.dev .

script:
  - docker run olehhutsuliak/docker-practice npm run test -- --coverage
