sudo: required

services:
  - docker

before_install:
  - docker build -t olehhutsuliak/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true olehhutsuliak/docker-practice npm run test
