sudo: required

services:
  - docker

before_install:
  - docker build -t olehhutsuliak/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true olehhutsuliak/docker-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-026551754503'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: '$AWS_ACCESS_KEY'
  secret_access_key: '$AWS_SECRET_KEY'
